import time

def personajes():
    print("1. Rey")
    print("2. Principe")
    print("3. Guardia real")
    print("4. Campesino")
    print("5. Salir\n")
    return


def edad_Rey():
    print("Eres un hombre experimentado.")
    time.sleep(1)
    print("Quien ha vivido viendo los errores de los que lo rodean.")
    time.sleep(1)
    print("Fuiste testigo de guerras antes de que los más jóvenes aprendieran a caminar.")
    time.sleep(1)
    print("Has recorrido todos lo rincones que has podido encontrar.")
    time.sleep(1)
    print("Gracias a esto, fuiste capaz de hallar un artefacto perdido en las ruinas de Noreval")
    time.sleep(1)
    print("El Ojo de Itharel")
    time.sleep(1)
    print("El Ojo es una gema incrustada en una cadena de hueso antiguo, que revela lo oculto a quien esté dispuesto a ver.")
    time.sleep(1)
    print("Con él, ves más allá de las palabras")
    time.sleep(1)
    print("las intenciones")
    time.sleep(1)
    print("incluso de la muerte.")
    time.sleep(1)
    print("Pero esta cercanía con la magia te obligó a portar un medallón con inscripciones arcanas.")
    time.sleep(1)
    print("Un antiguo amuleto que no emite luz ni calor, pero su presencia es firme, casi viva.")
    time.sleep(1)
    print("No lo llevas como adorno, sino como escudo.")
    time.sleep(1)
    return
    

def presen_Rey():
    print("1. Directo.")
    print("2. Burlesco.")
    print("3. Amenazante.")
    print("4. Amable.")
    presen_opcion = int(input())
    if presen_opcion == 1:
        print("Hablas con autoridad.")
        time.sleep(1)
        print("'Soy el nuevo rey de Nayhem.'")
        time.sleep(1)
        print("'No adornaré mis palabras ni perderé el tiempo con formalidades.'")
        time.sleep(1)
        print("'No busco agrado.'")
        time.sleep(1)
        print("'Busco orden.'")
        time.sleep(1)
        print("'Este reino no se sostendrá con palabras bonitas.'")
        time.sleep(1)
        print("'Sino con decisiones firmes.'")
        time.sleep(1)
        print("'He visto tronos arder y promesas romperse bajo el peso de la cobardía.'")
        time.sleep(1)
        print("'No cometeré los errores de mis predecesores.'")
        time.sleep(1)
        print("'No me doblegaré.")
        time.sleep(1)
        print("'Vine a gobernar, no vine a complacer.'")
        time.sleep(1)
        print("'Seré la línea que separa el caos del orden.'")
        time.sleep(1)
        print("'El último muro entre este reino y su ruina.'")
        time.sleep(1)
        print("'Si luchas por Nayhem, te daré mi espada.'")
        time.sleep(1)
        print("'Si lo amenazas, conocerás su filo.'")
        time.sleep(1)
        print("'Pero mientras yo respire, Nayhem no caerá.'")
        time.sleep(1)
        print(".............................")
        time.sleep(2)
        print("Tu discurso fue escuchado atentamente.")
        time.sleep(1)
        print("Por ultimo, puedes...")
        time.sleep(1)
        print("1. Blandir tu espada.")
        print("2. Retirarte.")
        AccFinal = int(input())
        if AccFinal == 1:
            print("Alzas tu espada ante la mirada de tu pueblo.")
            time.sleep(1)
            print("El acero brilla, resplandece.")
            time.sleep(1)
            print("Imponente, firme, como tu voluntad.")
            time.sleep(1)
            print("Envainas tu espada, y das media vuelta.")
            time.sleep(1)
            print("Desapareciendo tras las cortinas de tu palacio.")
            time.sleep(1)
            print("Tus palabras han dejado una marca en tu pueblo.")
            time.sleep(1)
            return
        elif AccFinal == 2:
            print("Luciendo satisfecho con lo recitado.")
            time.sleep(1)
            print("Te das media vuelta y desapareces en tu palacio.")
            time.sleep(1)
            return
    elif presen_opcion == 2:
        print("La edad puede traer sus ventajas, y también sus desafíos.")
        time.sleep(1)
        print("Algunos prefieren pensar que los años pesan más que la voluntad.")
        time.sleep(1)
        print("Pero hoy yo estoy aquí, al frente, viendo más que muchos que creen saberlo todo.")
        time.sleep(1)
        print("Que murmuren y señalen todo lo que quieran.")
        time.sleep(1)
        print("Solo son pequeños juegos de poder sin importancia.")
        time.sleep(2)
        print("No es mi intención entretenerme con sus risas ni con sus susurros a mis espaldas.")
        time.sleep(1)
        print("Aunque a veces, debo admitir, me divierte la ingenuidad con la que pretenden subestimarme.")
        time.sleep(1)
        print("Se creen astutos y fuertes, pero solo son piezas en un tablero que yo controlo.")
        time.sleep(1)
        print("Mientras ellos gastan energía en conspirar, yo preparo cada movimiento.")
        time.sleep(1)
        print("Porque cuando llegue el momento decisivo, recordarán quién lleva la corona.")
        time.sleep(1)
        print("Por eso, no temo a sus voces, ni a sus acciones ocultas.")
        time.sleep(1)
        print("Al final, seré yo quien decida qué queda de este reino y qué se pierde en el olvido.")
        time.sleep(1)
        print("...................")
        time.sleep(2)
        print("Tu discurso sembró inquietud.")
        time.sleep(1)
        print("Por ultimo puedes..")
        print("1. Esbozar una sonrisa irónica.")
        print("2. Retirarte.")
        AccFinal = int(input(""))
        if AccFinal == 1:
            print("Una leve sonrisa se dibuja en tus labios, casi imperceptible.")
            time.sleep(1)
            print("No hace falta que levantes la voz ni empuñes tu espada.")
            time.sleep(1)
            print("con ese gesto dejas claro que sabes más de lo que aparentas.")
            time.sleep(1)
            print("Tus palabras provocan susurros entre la multitud.")
            time.sleep(1)
            print("Algunos fruncen el seño.")
            time.sleep(1)
            print("Otros intercambian miradas.")
            time.sleep(1)
            print("Se siente la tensión en el aire.")
            time.sleep(1)
            print("Nadie sabe con certeza qué buscas ni qué clase de líder serás.")
            time.sleep(1)
            print("Sin previo aviso, te das vuelta y te marchas.")
            time.sleep(1)
            print("Dejando a tu pueblo con más preguntas que respuestas.")
            time.sleep(1)
        elif AccFinal == 2:
            print("No dices nada más.")
            time.sleep(1)
            print("Lentamente te das vuelta, alejandote de los ojos de la multitud.")
            time.sleep(1)
            print("Tus subditos no saben que sentir")
            time.sleep(1)
            print("Nadie esta seguro de tus intenciones")
            time.sleep(1)
    elif presen_opcion == 3:
        print
    elif presen_opcion == 4:
        print