def personajes():
    print("1. Rey")
    print("2. Principe")
    print("3. Guardia real")
    print("4. Campesino\n")


def camino_edad(edad):
    if edad >= 70:
        print("Eres un hombre experimentado.")
        print("Quien ha vivido viendo los errores de los que lo rodean.")
        print("Fuiste testigo de guerras antes de que los más jóvenes aprendieran a caminar.")
        print("Has recorrido todos lo rincones que has podido encontrar.")
        print("Gracias a esto, fuiste capaz de hallar un artefacto perdido en las ruinas de Noreval")
        print("El Ojo de Itharel")
        print("El Ojo es una gema incrustada en una cadena de hueso antiguo, que revela lo oculto a quien esté dispuesto a ver.")
        print("Con él, ves más allá de las palabras")
        print("las intenciones")
        print("incluso de la muerte.")
        print("Pero esta cercanía con la magia te obligó a portar un medallón con inscripciones arcanas.")
        print("Un antiguo amuleto que no emite luz ni calor, pero su presencia es firme, casi viva.")
        print("No lo llevas como adorno, sino como escudo.")
        return
    elif edad >= 55:
        print("Eres un hombre dedicado.")
        print("Has cometido errores y aprendido de ellos.")
        print("No necesitas probar nada, tus cicatrices hablan por ti.")
        print("Los más jóvenes te observan buscando guía, aunque pocos comprenden el peso que llevas.")
        print("Llevas puestos unos guanteletes reforzados, que han protegido tus manos en incontables batallas.")
        print("Tu arma no es una espada brillante ni un arco veloz, sino la 'Hoja del Juicio Tardío'")
        print("una espada de filo envejecido, pesada pero firme")
    elif edad >= 40:
        print("Eres un hombre con responsabilidades.")
        print("Tu mayor preocupación es tu familia, a quienes has jurado proteger")
        print("El peso de tus decisiones no solo afectan al reino, sino que también a los que amas.")
        print("Llevas un colgante con un diente de lobo, trofeo de una batalla pasada.")
        print("Representa tu fuerza y la protección feroz que ofreces a los tuyos.")
        print("Tu arma es el 'Filo de la Duda'")
        print("Una lanza de hierro templado, recta como tu intención pero pesada como tu conciencia.")
    elif edad >=30:
        print("Eres joven, con la mirada firme y las manos aún dispuestas a aprender.")
        print("Has vivido lo suficiente para perder algo, y lo justo para querer proteger lo que queda.")
        print("Muchos confunden juventud con ignorancia, sin notar que algunas heridas llegan antes que los años.")
        print("Llevas contigo una bufanda deshilachada, anudada al brazo.")
        print("La recogiste del barro tras el cruce de Lareth, cuando todo quedó en silencio.")
        print("Aún conserva el olor a humo y tierra húmeda.")
        print("Nadie te preguntó por qué la guardaste, y tú nunca ofreciste explicación.")
        print("A veces, el viento la sacude sin razón aparente, como si alguien todavía marchara a tu lado.")
        print("Tu arma es una hoja ligera, sin adornos, pero afilada como tu determinación.")
        print("No luchas por un trono, ni por venganza.")
        print("Luchas porque si no lo haces tú, nadie más lo hará.")
    elif edad >= 18:
        print("Eres joven, lleno de sueños pero aún inexperto.")
        print("El reino duda de ti por tu corta edad.")
        print("Sus miradas y palabras pesan más que cualquier arma.")
        print("Sientes la soledad de tener que probar tu valor.")
        print("En tu muñeca, un brazalete de tela te da fuerza silenciosa.")
        print("Cada vez que lo miras o lo sientes en tu piel, te recuerda que no estás solo en este camino.")
        print("Aunque no sabes qué deparará el futuro, ese brazalete es un símbolo silencioso de apoyo y valor.")
        print("Tu arma es una espada sencilla, de hoja humilde pero firme en tu mano.")
        print("No es solo metal y madera; es un símbolo de todo lo que esperas llegar a ser.")
        print("Cada vez que la empuñas, el frío de su filo te recuerda el precio de la batalla.")
        print("Sin embargo, tu determinación arde con más fuerza que cualquier miedo.")